# Hériter des bases Amlogic
. $ARCHIVE_CONF_DIR/sources/families/include/meson64_common.inc

# Forcer le noyau EDGE
KERNEL_BRANCH="edge"
# Si vous voulez tester une version spécifique (ex: 7.0-rc)
# KERNEL_TAG="v7.0" 

# Gardez un U-Boot récent pour supporter les nouvelles fonctionnalités du noyau
UBOOT_BRANCH="v2024.01" 
