# Hériter des bases Amlogic
. config/sources/families/include/meson64_common.inc

# On force les versions que l'on souhaite
UBOOT_BRANCH="v2023.07"
UBOOT_TAG="v2023.07"

# Configuration du noyau (Mainline)
KERNEL_BRANCH="6.1.x"
KERNEL_TAG="v6.1"

# Forcer le noyau EDGE
#KERNEL_BRANCH="current"
# Si vous voulez tester une version spécifique (ex: 7.0-rc)
# KERNEL_TAG="v7.0" 

# Gardez un U-Boot récent pour supporter les nouvelles fonctionnalités du noyau
#UBOOT_BRANCH="v2024.01" 
