# Hériter des bases Amlogic
. config/sources/families/include/meson64_common.inc

# On force les versions que l'on souhaite
UBOOT_BRANCH="v2023.07"
UBOOT_TAG="v2023.07"
BOOTBRANCH="${BOOTBRANCH_BOARD:-"tag:v2023.07"}"
BOOTPATCHDIR="${BOOTPATCHDIR:-"v2023.07"}"
 
