# Hériter des bases Amlogic
. config/sources/families/include/meson64_common.inc

# On force les versions que l'on souhaite
UBOOT_BRANCH="v2026.04"
UBOOT_TAG="v2026.04"
BOOTBRANCH='tag:v2026.04'
BOOTPATCHDIR='v2026.04'


 
