config:

  # .dts files in these directories will be copied as-is to the build tree; later ones overwrite earlier ones.
  # This is meant to provide a way to "add a board DTS" without having to null-patch them in.
  dts-directories:
    - { source: "dt_32", target: "arch/arm64/boot/dts/amlogic" }


 
